debug:
	zig build --summary all

release-safe:
	zig build -Doptimize=ReleaseSafe --summary all

release-small:
	zig build -Doptimize=ReleaseSmall --summary all

release-fast:
	zig build -Doptimize=ReleaseFast --summary all
